_target_: ml.datamodule.datasets.UnlabeledEmbeddingsSlideDataset
labeled: False
uris: ???
paths: ???
embeddings_col: ???
qc_and_tissue_thresholds: ${data.dataset.thresholds}
carcinoma_prediction_threshold: null
apply_carcinoma_prediction_filter: False
labels_map: null
