_target_: ml.datamodule.datasets.WeaklyLabeledEmbeddingsSlideDataset
uris: ???
paths: ???
embeddings_col: ???
fold: ???
invert_fold_selection: ???
qc_and_tissue_thresholds: ${data.dataset.thresholds}
labels_map: ${labels_map}
