[project]
name = "project-name"
version = "0.1.0"
authors = []
requires-python = ">=3.12,<3.14"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = [
    "torch>=2.9.0",
    "lightning>=2.4.0",
    "torchmetrics>=1.4.1",
    "rationai-sdk>=0.1.0",
    "rationai-tiling==1.1.1",
    "ratiopath>=1.4.2",
    "datasets>=4.0.0",
    "mlflow>=3.10.1",
    "rationai-mlkit>=0.4.1",
]

[project.optional-dependencies]
job = ["rationai-kube-jobs"]

[tool.uv.sources]
rationai-sdk = { git = "https://gitlab.ics.muni.cz/rationai/infrastructure/rationai-sdk-python.git" }
rationai-kube-jobs = { git = "ssh://git@gitlab.ics.muni.cz/rationai/infrastructure/kube-jobs" }
rationai-tiling = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/libraries/tiling.git" }
ratiopath = { git = "https://github.com/RationAI/ratiopath.git" }
report = { git = "https://gitlab.ics.muni.cz/rationai/digital-pathology/tools/report.git" }
rationai-mlkit = { git = "https://github.com/RationAI/mlkit.git" }

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "mypy",
    "report",
    "ruff",
    "seaborn>=0.13.2",
]
