# @package _global_

defaults:
  - base
  - _self_

level: ???
output_path: ???

artifact_paths:
  tissue_masks: tissue_masks
  processing_results: processing_results

metadata:
  run_name: Tissue Masks
  description: ???
