defaults:
  - _self_
  - decode_head@decode_head: embedding_classifier

_target_: ml.embedding_model.AdamWEmbeddingGleasonModel
num_classes: 3
lr: ???
weight_decay: ???
adamw_kwargs: {}
decode_head:
  in_features: 2560
  out_features: ${..num_classes}
  dropout_probability: 0
