defaults:
  - hydra: default
  - logger: mlflow
  - _self_

data_path: /mnt/data/MOU/prostate/
project_path: /mnt/projects/prostate_cancer/gleason/

metadata:
  experiment_name: Prostate Gleason Grading
