defaults:
  - base
  - _self_
  - /experiment: ???

seed: ${random_seed:}

mode: ???

model: {}
model_name: ???
checkpoint: ???

callbacks: {}
trainer: {}

datamodule: {}
data:
  dataset:
    name: ???

metadata:
  run_name: "Stage=${mode} Model=${model_name} Data=${data.dataset.name} Seed=${seed}"
  description: "Stage=${mode} Model=${model_name} Data=${data.dataset.name} Seed=${seed}"
