defaults:
  - datasets@train: embeddings/labeled
  - datasets@val_tl: embeddings/labeled
  - datasets@val_sl: embeddings/labeled
  - datasets@test_tl: embeddings/labeled
  - datasets@test_sl: embeddings/labeled
  - datasets@predict: embeddings/unlabeled
  - samplers@sampler: stratified_weighted_random

_target_: ml.datamodule.data_module.DataModule
batch_size: ???
drop_last: true
shuffle: true
num_workers: ???
train:
  apply_carcinoma_prediction_filter: True
val_tl:
  apply_carcinoma_prediction_filter: True
val_sl:
  apply_carcinoma_prediction_filter: False
test_tl:
  apply_carcinoma_prediction_filter: True
test_sl:
  apply_carcinoma_prediction_filter: False
