defaults:
  - datasets@train: embeddings/fully_labeled
  - datasets@val: embeddings/fully_labeled
  - datasets@test: embeddings/fully_labeled
  - datasets@predict: embeddings/unlabeled
  - samplers@sampler: stratified_weighted_random

_target_: ml.datamodule.SamplesDataModule
batch_size: ???
drop_last: true
shuffle: true
num_workers: ???
train:
  apply_carcinoma_prediction_filter: True
val:
  apply_carcinoma_prediction_filter: False
test:
  apply_carcinoma_prediction_filter: False
